### ISSUE TITLE
Dockerizar

### ISSUE THREAD

**Issue by alsuga** [librebeer/API_asorpereira#5]
deberiamos dockerizar para aislar los errores por el entorno y poderlo portar facil

**Comment by xergioalex** [comment]
Ya he completado esta tarea, revisar el pull request que subí: #11 

En el readme está toda la información sobre la dockerización.

**Comment by ivanchoff** [comment]
Que buen trabajo @xergioalex revisando lo que hizo he aprendido mucho de docker no sabia nada.
